# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: proto/process_presentation.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'proto/process_presentation.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n proto/process_presentation.proto\x12\x0cpresentation\"3\n\x0eProcessRequest\x12\x10\n\x08\x66ilepath\x18\x01 \x01(\t\x12\x0f\n\x07user_id\x18\x02 \x01(\t\"2\n\x0fProcessResponse\x12\x0f\n\x07task_id\x18\x01 \x01(\t\x12\x0e\n\x06status\x18\x02 \x01(\t2k\n\x15PresentationProcessor\x12R\n\x13ProcessPresentation\x12\x1c.presentation.ProcessRequest\x1a\x1d.presentation.ProcessResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.process_presentation_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PROCESSREQUEST']._serialized_start=50
  _globals['_PROCESSREQUEST']._serialized_end=101
  _globals['_PROCESSRESPONSE']._serialized_start=103
  _globals['_PROCESSRESPONSE']._serialized_end=153
  _globals['_PRESENTATIONPROCESSOR']._serialized_start=155
  _globals['_PRESENTATIONPROCESSOR']._serialized_end=262
# @@protoc_insertion_point(module_scope)
